# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 10:56
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
                'db_table': 'auth_user',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='\u5730\u5e02\u7f16\u7801')),
                ('name', models.CharField(max_length=128, verbose_name='\u5730\u5e02\u540d\u79f0')),
                ('type', models.IntegerField(verbose_name='\u5730\u5e02\u7c7b\u578b 30-\u7701 40-\u5e02 50-\u533a\u53bf')),
                ('pcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e0a\u7ea7\u5730\u5e02\u7f16\u7801')),
            ],
            options={
                'db_table': 't_city',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='\u529f\u80fd\u7f16\u7801')),
                ('api_action', models.CharField(max_length=128, null=True, verbose_name='\u63a5\u53e3')),
            ],
            options={
                'db_table': 't_role_menu',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u7ec4\u7ec7\u540d\u79f0')),
                ('pid', models.IntegerField(verbose_name='\u7236')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='beacon_user.City')),
            ],
            options={
                'db_table': 't_organization',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='\u5907\u6ce8')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=100, verbose_name='\u4e2d\u6587\u540d\u79f0')),
                ('img', models.CharField(max_length=128, verbose_name='\u7167\u7247')),
                ('sex', models.IntegerField(default=1, verbose_name='\u6027\u522b 1-\u7537 2-\u5973')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('telephone', models.CharField(max_length=20, verbose_name='\u7535\u8bdd')),
                ('idcard', models.CharField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('login_type', models.IntegerField(default=1, verbose_name='\u767b\u5f55\u65b9\u5f0f 1-\u7528\u6237\u540d\u5bc6\u7801 2-USB key 3-\u77ed\u4fe1\u9a8c\u8bc1\u7801')),
                ('comment', models.CharField(default='', max_length=256, verbose_name='\u7b80\u4ecb')),
                ('addr', models.CharField(default='', max_length=256, verbose_name='\u5730\u5740')),
                ('type', models.IntegerField(default=0, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
            options={
                'db_table': 't_user_info',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='beacon_user.Role'),
        ),
        migrations.AddField(
            model_name='beaconuser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon_user.Organization'),
        ),
        migrations.AddField(
            model_name='beaconuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon_user.Role'),
        ),
        migrations.AddField(
            model_name='beaconuser',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beacon_user.UserInfo'),
        ),
        migrations.AddField(
            model_name='beaconuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
