# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beacon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='code',
            new_name='app_code',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='ip',
            new_name='app_ip',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='city_id',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='applist',
            old_name='code',
            new_name='app_code',
        ),
        migrations.RenameField(
            model_name='applist',
            old_name='ip',
            new_name='app_ip',
        ),
        migrations.RenameField(
            model_name='applist',
            old_name='name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='applist',
            old_name='city_id',
            new_name='city_code',
        ),
    ]
