# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon_app', '0002_auto_20180308_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7aef\u53e3'),
        ),
        migrations.AddField(
            model_name='applist',
            name='app_port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ip\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e94\u7528\u7cfb\u7edf\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='app',
            name='city_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6240\u5c5e\u5730\u5e02'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='app_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ip\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='app_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5e94\u7528\u7cfb\u7edf\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='city_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6240\u5c5e\u5730\u5e02'),
        ),
    ]
