# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u7f16\u7801')),
                ('app_code', models.CharField(max_length=50, verbose_name='\u5e94\u7528\u7f16\u7801')),
                ('event_name', models.CharField(max_length=128, verbose_name='\u4e8b\u4ef6\u540d\u79f0')),
                ('event_type', models.IntegerField(default=0, verbose_name='\u4e8b\u4ef6\u7c7b\u578b 1-\u786e\u51ff\u7c7b\u4e8b\u4ef6 2-\u7591\u4f3c\u7c7b\u4e8b\u4ef6 3-\u9690\u60a3/\u98ce\u9669\u7c7b\u4e8b\u4ef6')),
                ('time', models.DateTimeField(verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('urgent_level', models.IntegerField(default=0, verbose_name='\u7d27\u6025\u7a0b\u5ea6')),
                ('source_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6e90ip')),
                ('source_port', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u6e90\u7aef\u53e3')),
                ('target_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u76ee\u7684')),
                ('target_port', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u76ee\u7684\u7aef\u53e3')),
                ('danger_level', models.IntegerField(default=0, verbose_name='\u4e25\u91cd\u7b49\u7ea7')),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.IntegerField(default=0, verbose_name='\u4e8b\u4ef6\u72b6\u6001 0-\u672a\u7b7e\u6536 1-\u7b7e\u6536\u529e\u7406\u4e2d 2-\u4e0b\u53d1\u529e\u7406\u4e2d 3-\u4e0a\u62a5\u529e\u7406\u4e2d 4-\u5df2\u529e\u7ed3')),
                ('file', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='\u9644\u4ef6')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('user_name', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'db_table': 't_event',
            },
        ),
        migrations.CreateModel(
            name='EventFlow',
            fields=[
                ('flow_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='\u552f\u4e00\u7f16\u7801')),
                ('app_code', models.CharField(max_length=50, verbose_name='\u5e94\u7528\u7f16\u7801')),
                ('event_code', models.CharField(max_length=50, verbose_name='\u4e8b\u4ef6\u7f16\u7801')),
                ('flow_type', models.IntegerField(default=1, verbose_name='\u6d41\u8f6c\u7c7b\u578b 1-\u4e0b\u53d1 2-\u4e0a\u62a5')),
                ('flow_comment', models.CharField(default='', max_length=256, verbose_name='\u6d41\u8f6c\u5907\u6ce8')),
                ('flow_user_id', models.IntegerField(blank=True, null=True, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('flow_user_name', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('flow_examine', models.IntegerField(default=0, verbose_name='\u662f\u5426\u9700\u8981\u5ba1\u6838 0-\u4e0d\u9700\u8981 1-\u9700\u8981')),
                ('flow_result', models.CharField(default='', max_length=256, verbose_name='\u53cd\u9988\u7ed3\u679c')),
                ('flow_status', models.IntegerField(default=0, verbose_name='\u6d41\u8f6c\u72b6\u6001 0-\u672a\u7b7e\u6536 1-\u7b7e\u6536\u529e\u7406\u4e2d 2-\u5df2\u529e\u7ed3 4-\u4e0a\u62a5\u81f3\u5176\u4ed6\u5e94\u7528\u4e8e\u7cfb\u7edf\u7cfb\u7edf 5-\u4e0b\u53d1\u81f3\u5176\u4ed6\u5e94\u7528\u7cfb\u7edf')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
            options={
                'db_table': 't_event_flow',
            },
        ),
    ]
